//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        public ESTUDIANTE()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.PENSION = new HashSet<PENSION>();
        }
    
        public int id_estudiante { get; set; }
        public string dni { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual ICollection<PENSION> PENSION { get; set; }
    }
}
