//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public int id_matricula { get; set; }
        public int id_estudiante { get; set; }
        public string nivel { get; set; }
        public decimal monto_matricula { get; set; }
        public System.DateTime fecha_m { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
    }
}
