//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_MATRICULAEntities : DbContext
    {
        public BD_MATRICULAEntities()
            : base("name=BD_MATRICULAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ESTUDIANTE> ESTUDIANTE { get; set; }
        public DbSet<MATRICULA> MATRICULA { get; set; }
        public DbSet<PENSION> PENSION { get; set; }
    }
}
